### ISSUE TITLE
Error with nornir_jinja

### ISSUE THREAD

**Issue by ghost** [nornir-automation/nornir_jinja2#10]
Hey guys,

Hope you can help me with this, I built a simple Nornir script following along a CBT course. Basically copied the script but it errors out. All my other Nornir scripts are fine - it's just the one with Jinja in it that errors out.

This is the script;
```
from nornir import InitNornir
from nornir_scrapli.tasks import send_configs
from nornir_utils.plugins.functions import print_result
from nornir_jinja2.plugins.tasks import template_file

nr = InitNornir(config_file="config.yaml")

def test_templates(task):
    template = task.run(task="template_file", template="snmp.j2", path="configs_jinja2")
    task.host["snmp_config"] = template.result
    rendered = task.host["snmp_config"]
    configuration = rendered.splitlines()
    task.run(task=send_configs, configs=configuration)

results = nr.run(task=test_templates)
print_result(results)
```

This is the error:
test_templates******************************************************************
* SWITCH ** changed : False **********************************************
vvvv test_templates ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "templatetest.py", line 13, in test_templates
    template = task.run(task="template_file", template="snmp.j2", path="configs_jinja2")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

The snmp.j2 file has a simple line:
```snmp-server location {{ host['snmp']['loc'] }}```

Additional info:
My environment is a Ubuntu instance via Multipass. This has python3 installed, plus the nornir, nornir_jinja, nornir_scrapli plugins. I tested it both on a Mac (ARM) and Windows (x86) environment.

Any idea what is wrong? Thanks!

**Comment by dbarrosop** [comment]
You are passing a string instead of a task here `template = task.run(task="template_file", template="snmp.j2", path="configs_jinja2")`.
